### ISSUE TITLE
Mypaint Brushes - Brush Management

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz_docs#136]
This is a review of various MyPaint updates that will and will not get included in the v1.4 release.

MyPaint updates merged since v1.3 that will be in v1.4 include:
- [x] opentoonz/opentoonz#2768 MyPaint libmypaint 1.4.0 Released
- [x] opentoonz/opentoonz#2763 Support for MyPaint brush format version 2
- [x] opentoonz/opentoonz#2769 libmypaint DLL update 
These update Mypaint DLL for windows to Mypaint v1.4, resolve a crash and allow use of older MyPaint brush packs.

Note that none of those other older brush packs are currently included in v1.4
There are potentially several hundred brushes that could be added to Opentoonz. 

**Question:**  Is it advisable that we add more MyPaint brushes before improving brush management?

ANSWER:  Not until brush management solution is added to Opentoonz.

An additional brush set for newer brushes was previously identified here:  
- [ ] opentoonz/opentoonz#2014 Add 'Good Pack' MyPaint brush pack
This didn't get included in the v1.3 release and there may be some issues preventing inclusion.
Recommend fully testing these brushes prior to inclusion.

Over all Status/documentation:
- [x] Update Mypaint DLL
- [x] Resolve conflict/crash caused by presence of Mypaint installation
- [ ] Internal brush management options and shortfalls (Update:  As of Jan 2022 Tahoma2D has brush managment system not yet ported to Opentoonz)  
- [ ] External brush management options (operating system, MyPaint, etc.)
- [ ] Additional old brush sets (early version of brushes)
- [ ] Additional new brush sets (standard version of brushes)
- [ ] Advanced capabilities of MyPaint Brushes (Note:  Not anticipated in near future)
- [ ] Review current MyPaint features in Mypaint, Krita, Opentoonz and other applications 
- [ ] Differences (advantages/disadvantages) of MyPaint brushes on raster vs Toonz raster levels.

_This listing does not suggest these line items should be implemented but rather lists them for review purposes._

It would be ideal to determine by 15 December what if any MyPaint changes are desired for inclusion in next release.  
This will then set the stage for future MyPaint development.
